name: Docker Image CI

on:
  workflow_call:
    inputs:
      docker_context:
        required: true
        type: string
      docker_image:
        required: true
        type: string
    secrets:
      MAVEN_USER:
        required: true
      MAVEN_PASSWORD:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lzk90s/java-develop-env:maven3-openjdk11
      volumes:
        - /root/.m2:/root/.m2
    env:
      MAVEN_USER: ${{secrets.MAVEN_USER}}
      MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
      REGISTRY: registry.cn-hangzhou.aliyuncs.com
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AliYun Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use cache
        uses: actions/cache@v3
        env:
          CACHE_NAME: cache-for-gsx
        with:
          path: /root/.m2
          key: ${{ runner.os }}-maven-${{ env.CACHE_NAME }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Init builder env
        run: init_env.sh

      - name: Build with maven
        run: mvn -Dmaven.test.skip=true -B package

      - name: Build and push docker
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.docker_context }}
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ inputs.docker_image }}:${{ env.BRANCH }}